// <auto-generated />
namespace Project_DotNET.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class En_coursbool : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(En_coursbool));
        
        string IMigrationMetadata.Id
        {
            get { return "201601312240145_En_cours - bool"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
